---
- hosts: webservers
  become: True
  tasks:
    - name: Install ApacheWebServer
      yum:
        name: httpd
        state: present
    - name: Start services
      service:
        name: httpd
        state: started
        enabled: True
    -name: Deplay Static Website
      copy:
        src: index.html
        dest: /var/www/html/
